# Generated by Django 6.0.3 on 2026-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimiento_motivo_movimiento_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.IntegerField(default=0),
        ),
    ]
