# Generated by Django 6.0.2 on 2026-04-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_stock_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('es_admin', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inventario.sugerencia')),
            ],
        ),
    ]
