# Generated by Django 6.0.2 on 2026-04-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_respuestasugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descontinuado',
            field=models.BooleanField(default=False),
        ),
    ]
