# Generated by Django 6.0.2 on 2026-04-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_descontinuado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_domicilio',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
