# Generated by Django 6.0.2 on 2026-04-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_pedido_valor_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallaproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tallaproducto',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2', 'Talla 2 (2 años)'), ('4', 'Talla 4 (4 años)'), ('6', 'Talla 6 (6 años)'), ('8', 'Talla 8 (8 años)'), ('10', 'Talla 10 (10 años)'), ('12', 'Talla 12 (12 años)')], max_length=5),
        ),
    ]
