# Generated by Django 6.0.2 on 2026-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_tallaproducto_stock_alter_tallaproducto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallaproducto',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('6', 'Talla 6'), ('8', 'Talla 8'), ('10', 'Talla 10'), ('12', 'Talla 12'), ('14', 'Talla 14'), ('16', 'Talla 16'), ('18', 'Talla 18')], max_length=5),
        ),
    ]
