# Generated by Django 6.0.2 on 2026-04-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_tallaproducto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
    ]
