# Generated by Django 6.0.2 on 2026-04-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_movimiento_nombre_producto_alter_movimiento_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
