# Generated by Django 6.0.2 on 2026-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_add_proveedor_to_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
