BARRIOS_BOGOTA = [
    # USAQUÉN
    {"nombre": "Cedritos", "localidad": "Usaquen"},
    {"nombre": "Santa Barbara", "localidad": "Usaquen"},
    {"nombre": "Chico Norte", "localidad": "Usaquen"},
    {"nombre": "Usaquen Centro", "localidad": "Usaquen"},
    {"nombre": "Verbenal", "localidad": "Usaquen"},
    {"nombre": "Toberin", "localidad": "Usaquen"},
    {"nombre": "San Cristobal Norte", "localidad": "Usaquen"},
    {"nombre": "Bella Suiza", "localidad": "Usaquen"},
    {"nombre": "Bosque de Pinos", "localidad": "Usaquen"},
    {"nombre": "El Codito", "localidad": "Usaquen"},
    {"nombre": "Horizontes", "localidad": "Usaquen"},
    {"nombre": "La Estrellita", "localidad": "Usaquen"},
    {"nombre": "Los Consuelos", "localidad": "Usaquen"},
    {"nombre": "Maranta", "localidad": "Usaquen"},
    {"nombre": "Maturin", "localidad": "Usaquen"},
    {"nombre": "Mirador del Norte", "localidad": "Usaquen"},
    {"nombre": "Nuevo Horizonte", "localidad": "Usaquen"},
    {"nombre": "San Antonio Norte", "localidad": "Usaquen"},
    {"nombre": "Tibabita", "localidad": "Usaquen"},
    {"nombre": "Villa del Mar", "localidad": "Usaquen"},
    {"nombre": "Country Club", "localidad": "Usaquen"},
    {"nombre": "La Calleja", "localidad": "Usaquen"},
    {"nombre": "Barrancas", "localidad": "Usaquen"},
    {"nombre": "Contador", "localidad": "Usaquen"},
    {"nombre": "El Refugio", "localidad": "Usaquen"},
    {"nombre": "La Uribe", "localidad": "Usaquen"},
    {"nombre": "Los Cedros", "localidad": "Usaquen"},
    {"nombre": "Niza Norte", "localidad": "Usaquen"},
    {"nombre": "San Patricio", "localidad": "Usaquen"},
    {"nombre": "Serrezuela", "localidad": "Usaquen"},
    {"nombre": "Soratama", "localidad": "Usaquen"},
    {"nombre": "Torca", "localidad": "Usaquen"},
    {"nombre": "Unicerros", "localidad": "Usaquen"},
    {"nombre": "Villa Nidia", "localidad": "Usaquen"},
    {"nombre": "Batan", "localidad": "Usaquen"},
    {"nombre": "La Cita", "localidad": "Usaquen"},
    {"nombre": "San Jose del Prado", "localidad": "Usaquen"},
    {"nombre": "Apartamentos El Refugio", "localidad": "Usaquen"},
    {"nombre": "Bosque Medina", "localidad": "Usaquen"},
    {"nombre": "Buque", "localidad": "Usaquen"},

    # CHAPINERO
    {"nombre": "Chapinero Alto", "localidad": "Chapinero"},
    {"nombre": "Chapinero Central", "localidad": "Chapinero"},
    {"nombre": "Rosales", "localidad": "Chapinero"},
    {"nombre": "El Nogal", "localidad": "Chapinero"},
    {"nombre": "La Cabrera", "localidad": "Chapinero"},
    {"nombre": "Quinta Camacho", "localidad": "Chapinero"},
    {"nombre": "Marly", "localidad": "Chapinero"},
    {"nombre": "Bosque Calderon", "localidad": "Chapinero"},
    {"nombre": "Antiguo Country", "localidad": "Chapinero"},
    {"nombre": "El Retiro", "localidad": "Chapinero"},
    {"nombre": "La Salle", "localidad": "Chapinero"},
    {"nombre": "Pardo Rubio", "localidad": "Chapinero"},
    {"nombre": "Sagrado Corazon", "localidad": "Chapinero"},
    {"nombre": "Sucre", "localidad": "Chapinero"},
    {"nombre": "El Castillo", "localidad": "Chapinero"},
    {"nombre": "La Porciuncula", "localidad": "Chapinero"},
    {"nombre": "Emaus", "localidad": "Chapinero"},
    {"nombre": "El Refugio", "localidad": "Chapinero"},
    {"nombre": "Bellavista", "localidad": "Chapinero"},
    {"nombre": "Los Rosales", "localidad": "Chapinero"},
    {"nombre": "San Martin de Porres", "localidad": "Chapinero"},
    {"nombre": "Lourdes", "localidad": "Chapinero"},
    {"nombre": "Granada", "localidad": "Chapinero"},
    {"nombre": "Chico Lago", "localidad": "Chapinero"},
    {"nombre": "Chico Norte", "localidad": "Chapinero"},
    {"nombre": "Chico Norte II", "localidad": "Chapinero"},
    {"nombre": "Chico Norte III", "localidad": "Chapinero"},
    {"nombre": "Juan XXIII", "localidad": "Chapinero"},
    {"nombre": "La Consolata", "localidad": "Chapinero"},
    {"nombre": "Miraflores", "localidad": "Chapinero"},
    {"nombre": "Multicentro", "localidad": "Chapinero"},
    {"nombre": "San Isidro Patios", "localidad": "Chapinero"},
    {"nombre": "Siberia", "localidad": "Chapinero"},
    {"nombre": "Villa Anita", "localidad": "Chapinero"},
    {"nombre": "Villa del Cerro", "localidad": "Chapinero"},
    {"nombre": "Belalcazar", "localidad": "Chapinero"},
    {"nombre": "El Paraiso", "localidad": "Chapinero"},
    {"nombre": "Ingemar", "localidad": "Chapinero"},
    {"nombre": "Cataluña", "localidad": "Chapinero"},
    {"nombre": "Nueva Autopista", "localidad": "Chapinero"},

    # SANTA FE
    {"nombre": "La Candelaria", "localidad": "Santa Fe"},
    {"nombre": "Las Nieves", "localidad": "Santa Fe"},
    {"nombre": "La Macarena", "localidad": "Santa Fe"},
    {"nombre": "Egipto", "localidad": "Santa Fe"},
    {"nombre": "Lourdes", "localidad": "Santa Fe"},
    {"nombre": "Miraflores", "localidad": "Santa Fe"},
    {"nombre": "San Martin", "localidad": "Santa Fe"},
    {"nombre": "Alameda", "localidad": "Santa Fe"},
    {"nombre": "Bavaria", "localidad": "Santa Fe"},
    {"nombre": "Belen", "localidad": "Santa Fe"},
    {"nombre": "La Concordia", "localidad": "Santa Fe"},
    {"nombre": "La Perseverancia", "localidad": "Santa Fe"},
    {"nombre": "Paloquemao", "localidad": "Santa Fe"},
    {"nombre": "San Victorino", "localidad": "Santa Fe"},
    {"nombre": "Santa Barbara", "localidad": "Santa Fe"},
    {"nombre": "Centro Administrativo", "localidad": "Santa Fe"},
    {"nombre": "La Favorita", "localidad": "Santa Fe"},
    {"nombre": "Las Cruces", "localidad": "Santa Fe"},
    {"nombre": "Los Laches", "localidad": "Santa Fe"},
    {"nombre": "Samper Mendoza", "localidad": "Santa Fe"},
    {"nombre": "San Bernardo", "localidad": "Santa Fe"},
    {"nombre": "Santa Ines", "localidad": "Santa Fe"},
    {"nombre": "Veracruz", "localidad": "Santa Fe"},
    {"nombre": "La Pepita", "localidad": "Santa Fe"},
    {"nombre": "La Sabana", "localidad": "Santa Fe"},
    {"nombre": "Ricaurte", "localidad": "Santa Fe"},
    {"nombre": "San Diego", "localidad": "Santa Fe"},
    {"nombre": "San Facade", "localidad": "Santa Fe"},
    {"nombre": "Bosque Izquierdo", "localidad": "Santa Fe"},
    {"nombre": "Circo de Toros", "localidad": "Santa Fe"},

    # SAN CRISTÓBAL
    {"nombre": "20 de Julio", "localidad": "San Cristobal"},
    {"nombre": "San Blas", "localidad": "San Cristobal"},
    {"nombre": "La Victoria", "localidad": "San Cristobal"},
    {"nombre": "Altamira", "localidad": "San Cristobal"},
    {"nombre": "Villa de los Alpes", "localidad": "San Cristobal"},
    {"nombre": "San Ignacio", "localidad": "San Cristobal"},
    {"nombre": "San Javier", "localidad": "San Cristobal"},
    {"nombre": "San Martin", "localidad": "San Cristobal"},
    {"nombre": "San Rafael", "localidad": "San Cristobal"},
    {"nombre": "San Vicente", "localidad": "San Cristobal"},
    {"nombre": "Santa Ines", "localidad": "San Cristobal"},
    {"nombre": "Santa Lucia", "localidad": "San Cristobal"},
    {"nombre": "Santa Marta", "localidad": "San Cristobal"},
    {"nombre": "Santa Rosa", "localidad": "San Cristobal"},
    {"nombre": "Santa Teresa", "localidad": "San Cristobal"},
    {"nombre": "Santa Barbara", "localidad": "San Cristobal"},
    {"nombre": "Santa Helena", "localidad": "San Cristobal"},
    {"nombre": "Santa Isabel", "localidad": "San Cristobal"},
    {"nombre": "Santa Clara", "localidad": "San Cristobal"},
    {"nombre": "Santa Ana", "localidad": "San Cristobal"},
    {"nombre": "Corinto", "localidad": "San Cristobal"},
    {"nombre": "El Quindio", "localidad": "San Cristobal"},
    {"nombre": "Fausto Prieto", "localidad": "San Cristobal"},
    {"nombre": "Juan Rey", "localidad": "San Cristobal"},
    {"nombre": "La Cecilia", "localidad": "San Cristobal"},
    {"nombre": "La Gloria", "localidad": "San Cristobal"},
    {"nombre": "La Paz", "localidad": "San Cristobal"},
    {"nombre": "Los Alpes", "localidad": "San Cristobal"},
    {"nombre": "Montecarlo", "localidad": "San Cristobal"},
    {"nombre": "Primero de Mayo", "localidad": "San Cristobal"},
    {"nombre": "Ramajal", "localidad": "San Cristobal"},
    {"nombre": "San Cristobal Sur", "localidad": "San Cristobal"},
    {"nombre": "Sosiego", "localidad": "San Cristobal"},
    {"nombre": "Union Familiar", "localidad": "San Cristobal"},
    {"nombre": "Villa del Cerro", "localidad": "San Cristobal"},
    {"nombre": "El Consuelo", "localidad": "San Cristobal"},
    {"nombre": "Guacamayas", "localidad": "San Cristobal"},
    {"nombre": "La Belleza", "localidad": "San Cristobal"},
    {"nombre": "Los Molinos", "localidad": "San Cristobal"},
    {"nombre": "Aguas Claras", "localidad": "San Cristobal"},

    # USME
    {"nombre": "Usme Centro", "localidad": "Usme"},
    {"nombre": "Santa Librada", "localidad": "Usme"},
    {"nombre": "Yomasa", "localidad": "Usme"},
    {"nombre": "Gran Yomasa", "localidad": "Usme"},
    {"nombre": "El Uval", "localidad": "Usme"},
    {"nombre": "El Nuevo Porvenir", "localidad": "Usme"},
    {"nombre": "Alfonso Lopez", "localidad": "Usme"},
    {"nombre": "La Flora", "localidad": "Usme"},
    {"nombre": "Chuniza", "localidad": "Usme"},
    {"nombre": "Comuneros", "localidad": "Usme"},
    {"nombre": "Danubio Azul", "localidad": "Usme"},
    {"nombre": "El Bosque", "localidad": "Usme"},
    {"nombre": "La Esperanza Sur", "localidad": "Usme"},
    {"nombre": "La Marichuela", "localidad": "Usme"},
    {"nombre": "Tocaimita", "localidad": "Usme"},
    {"nombre": "Virrey", "localidad": "Usme"},
    {"nombre": "La Fiscala", "localidad": "Usme"},
    {"nombre": "El Cortijo", "localidad": "Usme"},
    {"nombre": "El Triangulo", "localidad": "Usme"},
    {"nombre": "La Reforma", "localidad": "Usme"},
    {"nombre": "Los Comuneros", "localidad": "Usme"},
    {"nombre": "Brazuelos", "localidad": "Usme"},
    {"nombre": "El Destino", "localidad": "Usme"},
    {"nombre": "El Paramo", "localidad": "Usme"},
    {"nombre": "La Requilina", "localidad": "Usme"},
    {"nombre": "Los Soches", "localidad": "Usme"},
    {"nombre": "Olarte", "localidad": "Usme"},
    {"nombre": "Usme Pueblo", "localidad": "Usme"},
    {"nombre": "Valle de los Linos", "localidad": "Usme"},
    {"nombre": "Villa Anita", "localidad": "Usme"},
    {"nombre": "Ciudad Usme", "localidad": "Usme"},
    {"nombre": "El Recuerdo Sur", "localidad": "Usme"},
    {"nombre": "Las Violetas", "localidad": "Usme"},
    {"nombre": "Monteblanco", "localidad": "Usme"},
    {"nombre": "Porvenir", "localidad": "Usme"},
    {"nombre": "Serranias", "localidad": "Usme"},
    {"nombre": "Tiguaque", "localidad": "Usme"},
    {"nombre": "Villa Sandra", "localidad": "Usme"},
    {"nombre": "Barranquillita", "localidad": "Usme"},
    {"nombre": "Betania", "localidad": "Usme"},

    # TUNJUELITO
    {"nombre": "Tunjuelito", "localidad": "Tunjuelito"},
    {"nombre": "Venecia", "localidad": "Tunjuelito"},
    {"nombre": "Abraham Lincoln", "localidad": "Tunjuelito"},
    {"nombre": "El Faro", "localidad": "Tunjuelito"},
    {"nombre": "El Tunal", "localidad": "Tunjuelito"},
    {"nombre": "Isla del Sol", "localidad": "Tunjuelito"},
    {"nombre": "San Benito", "localidad": "Tunjuelito"},
    {"nombre": "Sierra Morena", "localidad": "Tunjuelito"},
    {"nombre": "Nuevo Muzu", "localidad": "Tunjuelito"},
    {"nombre": "Rincon de Mutis", "localidad": "Tunjuelito"},
    {"nombre": "Barrio Mexico", "localidad": "Tunjuelito"},
    {"nombre": "Bayona", "localidad": "Tunjuelito"},
    {"nombre": "Candelaria la Nueva", "localidad": "Tunjuelito"},
    {"nombre": "El Recuerdo", "localidad": "Tunjuelito"},
    {"nombre": "Fátima", "localidad": "Tunjuelito"},
    {"nombre": "La Picota", "localidad": "Tunjuelito"},
    {"nombre": "Muzu", "localidad": "Tunjuelito"},
    {"nombre": "Parque Metropolitano El Tunal", "localidad": "Tunjuelito"},
    {"nombre": "Perdomo", "localidad": "Tunjuelito"},
    {"nombre": "San Carlos", "localidad": "Tunjuelito"},
    {"nombre": "Santa Lucia", "localidad": "Tunjuelito"},
    {"nombre": "Samore", "localidad": "Tunjuelito"},
    {"nombre": "Villa Mayor", "localidad": "Tunjuelito"},
    {"nombre": "Villa Nelly", "localidad": "Tunjuelito"},
    {"nombre": "Vista Hermosa", "localidad": "Tunjuelito"},
    {"nombre": "El Vergel", "localidad": "Tunjuelito"},
    {"nombre": "Consuelo", "localidad": "Tunjuelito"},
    {"nombre": "Palermo Sur", "localidad": "Tunjuelito"},
    {"nombre": "San Jorge", "localidad": "Tunjuelito"},
    {"nombre": "Santa Isabel Sur", "localidad": "Tunjuelito"},

    # BOSA
    {"nombre": "Bosa Centro", "localidad": "Bosa"},
    {"nombre": "El Recreo", "localidad": "Bosa"},
    {"nombre": "San Bernardino", "localidad": "Bosa"},
    {"nombre": "La Libertad", "localidad": "Bosa"},
    {"nombre": "Porvenir", "localidad": "Bosa"},
    {"nombre": "Apogeo", "localidad": "Bosa"},
    {"nombre": "Bosa Nova", "localidad": "Bosa"},
    {"nombre": "Carlos Alban", "localidad": "Bosa"},
    {"nombre": "El Potrero", "localidad": "Bosa"},
    {"nombre": "Jimenez de Quesada", "localidad": "Bosa"},
    {"nombre": "La Amistad", "localidad": "Bosa"},
    {"nombre": "La Estacion", "localidad": "Bosa"},
    {"nombre": "Las Margaritas", "localidad": "Bosa"},
    {"nombre": "Laureles", "localidad": "Bosa"},
    {"nombre": "Palestina", "localidad": "Bosa"},
    {"nombre": "San Diego", "localidad": "Bosa"},
    {"nombre": "San Jose", "localidad": "Bosa"},
    {"nombre": "San Pablo", "localidad": "Bosa"},
    {"nombre": "Santa Fe", "localidad": "Bosa"},
    {"nombre": "Villa Nelly", "localidad": "Bosa"},
    {"nombre": "Antonia Santos", "localidad": "Bosa"},
    {"nombre": "Arrayanes", "localidad": "Bosa"},
    {"nombre": "Bosanova", "localidad": "Bosa"},
    {"nombre": "Brasilia", "localidad": "Bosa"},
    {"nombre": "El Amparo", "localidad": "Bosa"},
    {"nombre": "El Eden", "localidad": "Bosa"},
    {"nombre": "El Tintal", "localidad": "Bosa"},
    {"nombre": "Jose Antonio Galan", "localidad": "Bosa"},
    {"nombre": "La Independencia", "localidad": "Bosa"},
    {"nombre": "Las Margaritas II", "localidad": "Bosa"},
    {"nombre": "Los Almendros", "localidad": "Bosa"},
    {"nombre": "Maria Paz", "localidad": "Bosa"},
    {"nombre": "Naranjos", "localidad": "Bosa"},
    {"nombre": "Olarte", "localidad": "Bosa"},
    {"nombre": "Piamonte", "localidad": "Bosa"},
    {"nombre": "San Eugenio", "localidad": "Bosa"},
    {"nombre": "Trinidad", "localidad": "Bosa"},
    {"nombre": "Villa Clemencia", "localidad": "Bosa"},
    {"nombre": "Villa del Rio", "localidad": "Bosa"},
    {"nombre": "Escocia", "localidad": "Bosa"},

    # KENNEDY
    {"nombre": "Kennedy Central", "localidad": "Kennedy"},
    {"nombre": "Castilla", "localidad": "Kennedy"},
    {"nombre": "Tintal", "localidad": "Kennedy"},
    {"nombre": "Patio Bonito", "localidad": "Kennedy"},
    {"nombre": "Marsella", "localidad": "Kennedy"},
    {"nombre": "Timiza", "localidad": "Kennedy"},
    {"nombre": "Alqueria", "localidad": "Kennedy"},
    {"nombre": "Britalia", "localidad": "Kennedy"},
    {"nombre": "Villa Alsacia", "localidad": "Kennedy"},
    {"nombre": "Carvajal", "localidad": "Kennedy"},
    {"nombre": "La Igualdad", "localidad": "Kennedy"},
    {"nombre": "Americas", "localidad": "Kennedy"},
    {"nombre": "Bavaria", "localidad": "Kennedy"},
    {"nombre": "Corabastos", "localidad": "Kennedy"},
    {"nombre": "Gran Americas", "localidad": "Kennedy"},
    {"nombre": "La Alameda", "localidad": "Kennedy"},
    {"nombre": "Las Margaritas", "localidad": "Kennedy"},
    {"nombre": "Mandalay", "localidad": "Kennedy"},
    {"nombre": "Techo", "localidad": "Kennedy"},
    {"nombre": "Verona", "localidad": "Kennedy"},
    {"nombre": "Banderas", "localidad": "Kennedy"},
    {"nombre": "Calandaima", "localidad": "Kennedy"},
    {"nombre": "Catalina", "localidad": "Kennedy"},
    {"nombre": "El Jazmin", "localidad": "Kennedy"},
    {"nombre": "El Poblado", "localidad": "Kennedy"},
    {"nombre": "El Rincon", "localidad": "Kennedy"},
    {"nombre": "Hipotecho", "localidad": "Kennedy"},
    {"nombre": "La Campiña", "localidad": "Kennedy"},
    {"nombre": "La Chucua", "localidad": "Kennedy"},
    {"nombre": "Las Delicias", "localidad": "Kennedy"},
    {"nombre": "Llano Grande", "localidad": "Kennedy"},
    {"nombre": "Maria Paz", "localidad": "Kennedy"},
    {"nombre": "Pastrana", "localidad": "Kennedy"},
    {"nombre": "Patio Bonito II", "localidad": "Kennedy"},
    {"nombre": "Perpetuo Socorro", "localidad": "Kennedy"},
    {"nombre": "San Rafael", "localidad": "Kennedy"},
    {"nombre": "Santa Rosita", "localidad": "Kennedy"},
    {"nombre": "Valladolid", "localidad": "Kennedy"},
    {"nombre": "Villa Emilia", "localidad": "Kennedy"},
    {"nombre": "Villa Gladys", "localidad": "Kennedy"},

    # FONTIBÓN
    {"nombre": "Fontibon Centro", "localidad": "Fontibon"},
    {"nombre": "Villemar", "localidad": "Fontibon"},
    {"nombre": "Capellania", "localidad": "Fontibon"},
    {"nombre": "Modelia", "localidad": "Fontibon"},
    {"nombre": "San Pablo", "localidad": "Fontibon"},
    {"nombre": "Aeropuerto El Dorado", "localidad": "Fontibon"},
    {"nombre": "Bahia", "localidad": "Fontibon"},
    {"nombre": "Ciudad Hayuelos", "localidad": "Fontibon"},
    {"nombre": "El Carmen", "localidad": "Fontibon"},
    {"nombre": "El Refugio", "localidad": "Fontibon"},
    {"nombre": "La Cabana", "localidad": "Fontibon"},
    {"nombre": "La Estacion", "localidad": "Fontibon"},
    {"nombre": "La Isla", "localidad": "Fontibon"},
    {"nombre": "Puerta de Teja", "localidad": "Fontibon"},
    {"nombre": "Sabana Grande", "localidad": "Fontibon"},
    {"nombre": "San Jose", "localidad": "Fontibon"},
    {"nombre": "Zona Franca", "localidad": "Fontibon"},
    {"nombre": "Granjas de Techo", "localidad": "Fontibon"},
    {"nombre": "Kasandra", "localidad": "Fontibon"},
    {"nombre": "La Aldea", "localidad": "Fontibon"},
    {"nombre": "La Faena", "localidad": "Fontibon"},
    {"nombre": "La Giralda", "localidad": "Fontibon"},
    {"nombre": "La Holanda", "localidad": "Fontibon"},
    {"nombre": "La Palestina", "localidad": "Fontibon"},
    {"nombre": "Las Mercedes", "localidad": "Fontibon"},
    {"nombre": "Mantilla", "localidad": "Fontibon"},
    {"nombre": "Naranjos", "localidad": "Fontibon"},
    {"nombre": "Prados de Santa Barbara", "localidad": "Fontibon"},
    {"nombre": "San Andres", "localidad": "Fontibon"},
    {"nombre": "Santa Cecilia", "localidad": "Fontibon"},
    {"nombre": "Tequendama", "localidad": "Fontibon"},
    {"nombre": "Versalles", "localidad": "Fontibon"},
    {"nombre": "Villa Liliana", "localidad": "Fontibon"},
    {"nombre": "Camelia", "localidad": "Fontibon"},
    {"nombre": "Ciudad Hayuelos II", "localidad": "Fontibon"},
    {"nombre": "El Triunfo", "localidad": "Fontibon"},
    {"nombre": "Los Alamos", "localidad": "Fontibon"},
    {"nombre": "Metropolis", "localidad": "Fontibon"},
    {"nombre": "San Nicolas", "localidad": "Fontibon"},
    {"nombre": "Torremolinos", "localidad": "Fontibon"},

    # ENGATIVÁ
    {"nombre": "Engativa Pueblo", "localidad": "Engativa"},
    {"nombre": "Modelia", "localidad": "Engativa"},
    {"nombre": "Normandia", "localidad": "Engativa"},
    {"nombre": "Boyaca Real", "localidad": "Engativa"},
    {"nombre": "Garces Navas", "localidad": "Engativa"},
    {"nombre": "Las Ferias", "localidad": "Engativa"},
    {"nombre": "Minuto de Dios", "localidad": "Engativa"},
    {"nombre": "Santa Helenita", "localidad": "Engativa"},
    {"nombre": "La Estrada", "localidad": "Engativa"},
    {"nombre": "Bolivia", "localidad": "Engativa"},
    {"nombre": "Bonanza", "localidad": "Engativa"},
    {"nombre": "El Encanto", "localidad": "Engativa"},
    {"nombre": "Florencia", "localidad": "Engativa"},
    {"nombre": "La Cabana", "localidad": "Engativa"},
    {"nombre": "La Palmera", "localidad": "Engativa"},
    {"nombre": "La Riviera", "localidad": "Engativa"},
    {"nombre": "Las Mercedes", "localidad": "Engativa"},
    {"nombre": "Quirigua", "localidad": "Engativa"},
    {"nombre": "Santa Cecilia", "localidad": "Engativa"},
    {"nombre": "Villa Luz", "localidad": "Engativa"},
    {"nombre": "Albania", "localidad": "Engativa"},
    {"nombre": "Aloha", "localidad": "Engativa"},
    {"nombre": "Bachue", "localidad": "Engativa"},
    {"nombre": "Bochica", "localidad": "Engativa"},
    {"nombre": "Bosque Popular", "localidad": "Engativa"},
    {"nombre": "Cordoba", "localidad": "Engativa"},
    {"nombre": "El Muelle", "localidad": "Engativa"},
    {"nombre": "El Prados", "localidad": "Engativa"},
    {"nombre": "El Rubí", "localidad": "Engativa"},
    {"nombre": "Floralia", "localidad": "Engativa"},
    {"nombre": "Guadalupe", "localidad": "Engativa"},
    {"nombre": "Jardin Botanico", "localidad": "Engativa"},
    {"nombre": "La Española", "localidad": "Engativa"},
    {"nombre": "Los Ángeles", "localidad": "Engativa"},
    {"nombre": "Primavera", "localidad": "Engativa"},
    {"nombre": "Rio Negro", "localidad": "Engativa"},
    {"nombre": "San Joaquin", "localidad": "Engativa"},
    {"nombre": "Tabora", "localidad": "Engativa"},
    {"nombre": "Venezuela", "localidad": "Engativa"},
    {"nombre": "Villa Amalia", "localidad": "Engativa"},

    # SUBA
    {"nombre": "Suba Centro", "localidad": "Suba"},
    {"nombre": "Niza", "localidad": "Suba"},
    {"nombre": "Gratamira", "localidad": "Suba"},
    {"nombre": "Tibabuyes", "localidad": "Suba"},
    {"nombre": "Villa del Prado", "localidad": "Suba"},
    {"nombre": "Aures", "localidad": "Suba"},
    {"nombre": "La Campina", "localidad": "Suba"},
    {"nombre": "Compartir", "localidad": "Suba"},
    {"nombre": "Rincon", "localidad": "Suba"},
    {"nombre": "San Jose de Bavaria", "localidad": "Suba"},
    {"nombre": "Lisboa", "localidad": "Suba"},
    {"nombre": "Prado Veraniego", "localidad": "Suba"},
    {"nombre": "San Cipriano", "localidad": "Suba"},
    {"nombre": "La Alborada", "localidad": "Suba"},
    {"nombre": "El Pinar", "localidad": "Suba"},
    {"nombre": "La Gaitana", "localidad": "Suba"},
    {"nombre": "Mazuren", "localidad": "Suba"},
    {"nombre": "La Toscana", "localidad": "Suba"},
    {"nombre": "El Batan", "localidad": "Suba"},
    {"nombre": "San Pedro de Tibabuyes", "localidad": "Suba"},
    {"nombre": "Acacias", "localidad": "Suba"},
    {"nombre": "Aldea", "localidad": "Suba"},
    {"nombre": "Altos de Chozica", "localidad": "Suba"},
    {"nombre": "Bilbao", "localidad": "Suba"},
    {"nombre": "Britalia", "localidad": "Suba"},
    {"nombre": "Casa Blanca Suba", "localidad": "Suba"},
    {"nombre": "El Cerezo", "localidad": "Suba"},
    {"nombre": "El Corzo", "localidad": "Suba"},
    {"nombre": "El Rincon", "localidad": "Suba"},
    {"nombre": "Flores del Norte", "localidad": "Suba"},
    {"nombre": "Fontanar del Rio", "localidad": "Suba"},
    {"nombre": "Guicani", "localidad": "Suba"},
    {"nombre": "La Cabana", "localidad": "Suba"},
    {"nombre": "La Esperanza Norte", "localidad": "Suba"},
    {"nombre": "La Floresta", "localidad": "Suba"},
    {"nombre": "La Niña", "localidad": "Suba"},
    {"nombre": "Niza Sur", "localidad": "Suba"},
    {"nombre": "Pinar del Rio", "localidad": "Suba"},
    {"nombre": "Salitre", "localidad": "Suba"},
    {"nombre": "Tuna Alta", "localidad": "Suba"},

    # BARRIOS UNIDOS
    {"nombre": "Doce de Octubre", "localidad": "Barrios Unidos"},
    {"nombre": "Los Alcazares", "localidad": "Barrios Unidos"},
    {"nombre": "Polo Club", "localidad": "Barrios Unidos"},
    {"nombre": "Salitre", "localidad": "Barrios Unidos"},
    {"nombre": "Andes", "localidad": "Barrios Unidos"},
    {"nombre": "Avenida El Dorado", "localidad": "Barrios Unidos"},
    {"nombre": "Benjamin Herrera", "localidad": "Barrios Unidos"},
    {"nombre": "Colombia", "localidad": "Barrios Unidos"},
    {"nombre": "El Rosario", "localidad": "Barrios Unidos"},
    {"nombre": "Jorge Eliecer Gaitan", "localidad": "Barrios Unidos"},
    {"nombre": "La Castellana", "localidad": "Barrios Unidos"},
    {"nombre": "La Patria", "localidad": "Barrios Unidos"},
    {"nombre": "Meissen", "localidad": "Barrios Unidos"},
    {"nombre": "Niza Sur", "localidad": "Barrios Unidos"},
    {"nombre": "Rionegro", "localidad": "Barrios Unidos"},
    {"nombre": "Alcazar", "localidad": "Barrios Unidos"},
    {"nombre": "Arz Cundinamarca", "localidad": "Barrios Unidos"},
    {"nombre": "Camelia", "localidad": "Barrios Unidos"},
    {"nombre": "Copacabana", "localidad": "Barrios Unidos"},
    {"nombre": "El Batan", "localidad": "Barrios Unidos"},
    {"nombre": "El Encanto", "localidad": "Barrios Unidos"},
    {"nombre": "El Lago", "localidad": "Barrios Unidos"},
    {"nombre": "El Paraiso", "localidad": "Barrios Unidos"},
    {"nombre": "El Salitre", "localidad": "Barrios Unidos"},
    {"nombre": "La Aurora", "localidad": "Barrios Unidos"},
    {"nombre": "La Esmeralda", "localidad": "Barrios Unidos"},
    {"nombre": "La Merced Norte", "localidad": "Barrios Unidos"},
    {"nombre": "Los Lagartos", "localidad": "Barrios Unidos"},
    {"nombre": "Primero de Mayo", "localidad": "Barrios Unidos"},
    {"nombre": "Quirigua", "localidad": "Barrios Unidos"},

    # TEUSAQUILLO
    {"nombre": "Teusaquillo", "localidad": "Teusaquillo"},
    {"nombre": "Palermo", "localidad": "Teusaquillo"},
    {"nombre": "Galerias", "localidad": "Teusaquillo"},
    {"nombre": "La Soledad", "localidad": "Teusaquillo"},
    {"nombre": "Nicolas de Federman", "localidad": "Teusaquillo"},
    {"nombre": "Armenia", "localidad": "Teusaquillo"},
    {"nombre": "Ciudad Salitre Oriental", "localidad": "Teusaquillo"},
    {"nombre": "Ciudad Salitre Occidental", "localidad": "Teusaquillo"},
    {"nombre": "El Campin", "localidad": "Teusaquillo"},
    {"nombre": "La Esmeralda", "localidad": "Teusaquillo"},
    {"nombre": "Parque Simon Bolivar", "localidad": "Teusaquillo"},
    {"nombre": "Quinta Paredes", "localidad": "Teusaquillo"},
    {"nombre": "San Luis", "localidad": "Teusaquillo"},
    {"nombre": "Santa Matilde", "localidad": "Teusaquillo"},
    {"nombre": "Veinte de Julio", "localidad": "Teusaquillo"},
    {"nombre": "Acevedo Tejada", "localidad": "Teusaquillo"},
    {"nombre": "Alhambra", "localidad": "Teusaquillo"},
    {"nombre": "Campín Norte", "localidad": "Teusaquillo"},
    {"nombre": "Campín Sur", "localidad": "Teusaquillo"},
    {"nombre": "Cundinamarca", "localidad": "Teusaquillo"},
    {"nombre": "El Recuerdo", "localidad": "Teusaquillo"},
    {"nombre": "Garces Navas", "localidad": "Teusaquillo"},
    {"nombre": "La Magdalena", "localidad": "Teusaquillo"},
    {"nombre": "La Merced", "localidad": "Teusaquillo"},
    {"nombre": "Lavaderos", "localidad": "Teusaquillo"},
    {"nombre": "Medellin", "localidad": "Teusaquillo"},
    {"nombre": "Parque Bello Horizonte", "localidad": "Teusaquillo"},
    {"nombre": "Parkway", "localidad": "Teusaquillo"},
    {"nombre": "Sears", "localidad": "Teusaquillo"},
    {"nombre": "Simon Bolivar", "localidad": "Teusaquillo"},

    # LOS MÁRTIRES
    {"nombre": "La Sabana", "localidad": "Los Martires"},
    {"nombre": "Santa Isabel", "localidad": "Los Martires"},
    {"nombre": "Ricaurte", "localidad": "Los Martires"},
    {"nombre": "Eduardo Santos", "localidad": "Los Martires"},
    {"nombre": "El Liston", "localidad": "Los Martires"},
    {"nombre": "La Pepita", "localidad": "Los Martires"},
    {"nombre": "Samper Mendoza", "localidad": "Los Martires"},
    {"nombre": "Voto Nacional", "localidad": "Los Martires"},
    {"nombre": "Calvo Sur", "localidad": "Los Martires"},
    {"nombre": "El Progreso", "localidad": "Los Martires"},
    {"nombre": "Germania", "localidad": "Los Martires"},
    {"nombre": "La Estanzuela", "localidad": "Los Martires"},
    {"nombre": "La Favorita", "localidad": "Los Martires"},
    {"nombre": "Las Cruces", "localidad": "Los Martires"},
    {"nombre": "Los Martires", "localidad": "Los Martires"},
    {"nombre": "Santa Fe", "localidad": "Los Martires"},
    {"nombre": "Veraguas", "localidad": "Los Martires"},
    {"nombre": "Paloquemao", "localidad": "Los Martires"},
    {"nombre": "Cundinamarca", "localidad": "Los Martires"},
    {"nombre": "El Listón Norte", "localidad": "Los Martires"},
    {"nombre": "La Ensenada", "localidad": "Los Martires"},
    {"nombre": "Leon XIII", "localidad": "Los Martires"},
    {"nombre": "San Victorino", "localidad": "Los Martires"},
    {"nombre": "Restrepo", "localidad": "Los Martires"},
    {"nombre": "Trinidad", "localidad": "Los Martires"},
    {"nombre": "Colseguros", "localidad": "Los Martires"},
    {"nombre": "El Vergel", "localidad": "Los Martires"},
    {"nombre": "La Rivera", "localidad": "Los Martires"},
    {"nombre": "Murillo Toro", "localidad": "Los Martires"},
    {"nombre": "Quinta Ramos", "localidad": "Los Martires"},

    # ANTONIO NARIÑO
    {"nombre": "Ciudad Jardin Sur", "localidad": "Antonio Nariño"},
    {"nombre": "Restrepo", "localidad": "Antonio Nariño"},
    {"nombre": "Santander", "localidad": "Antonio Nariño"},
    {"nombre": "Antonio Nariño", "localidad": "Antonio Nariño"},
    {"nombre": "Policarpa", "localidad": "Antonio Nariño"},
    {"nombre": "Asuncion", "localidad": "Antonio Nariño"},
    {"nombre": "Consuelo", "localidad": "Antonio Nariño"},
    {"nombre": "Carvajal", "localidad": "Antonio Nariño"},
    {"nombre": "Murillo", "localidad": "Antonio Nariño"},
    {"nombre": "San Antonio", "localidad": "Antonio Nariño"},
    {"nombre": "Bravo Paez", "localidad": "Antonio Nariño"},
    {"nombre": "Centenario", "localidad": "Antonio Nariño"},
    {"nombre": "Ciudad Berna", "localidad": "Antonio Nariño"},
    {"nombre": "Claret", "localidad": "Antonio Nariño"},
    {"nombre": "El Likes", "localidad": "Antonio Nariño"},
    {"nombre": "El Vergel", "localidad": "Antonio Nariño"},
    {"nombre": "Fucha", "localidad": "Antonio Nariño"},
    {"nombre": "Granjas San Pablo", "localidad": "Antonio Nariño"},
    {"nombre": "La Trinidad", "localidad": "Antonio Nariño"},
    {"nombre": "Las Lomas", "localidad": "Antonio Nariño"},
    {"nombre": "Olaya Herrera", "localidad": "Antonio Nariño"},
    {"nombre": "Quiroga", "localidad": "Antonio Nariño"},
    {"nombre": "San Jorge", "localidad": "Antonio Nariño"},
    {"nombre": "San Marcos", "localidad": "Antonio Nariño"},
    {"nombre": "Santa Catalina", "localidad": "Antonio Nariño"},
    {"nombre": "Santa Isabel", "localidad": "Antonio Nariño"},
    {"nombre": "Sosiego", "localidad": "Antonio Nariño"},
    {"nombre": "Twelve de Octubre", "localidad": "Antonio Nariño"},
    {"nombre": "Union", "localidad": "Antonio Nariño"},
    {"nombre": "Valencia", "localidad": "Antonio Nariño"},

    # PUENTE ARANDA
    {"nombre": "Puente Aranda", "localidad": "Puente Aranda"},
    {"nombre": "Muzu", "localidad": "Puente Aranda"},
    {"nombre": "Zona Industrial", "localidad": "Puente Aranda"},
    {"nombre": "Galan", "localidad": "Puente Aranda"},
    {"nombre": "Cundinamarca", "localidad": "Puente Aranda"},
    {"nombre": "El Penon", "localidad": "Puente Aranda"},
    {"nombre": "Fuentes", "localidad": "Puente Aranda"},
    {"nombre": "La Pradera", "localidad": "Puente Aranda"},
    {"nombre": "Las Americas", "localidad": "Puente Aranda"},
    {"nombre": "Salazar Gomez", "localidad": "Puente Aranda"},
    {"nombre": "San Rafael Industrial", "localidad": "Puente Aranda"},
    {"nombre": "Valladolid", "localidad": "Puente Aranda"},
    {"nombre": "Alcala", "localidad": "Puente Aranda"},
    {"nombre": "Alqueria", "localidad": "Puente Aranda"},
    {"nombre": "Arroz", "localidad": "Puente Aranda"},
    {"nombre": "Bochica", "localidad": "Puente Aranda"},
    {"nombre": "El Cartón", "localidad": "Puente Aranda"},
    {"nombre": "El Eden", "localidad": "Puente Aranda"},
    {"nombre": "El Jazmin", "localidad": "Puente Aranda"},
    {"nombre": "Gorgonzola", "localidad": "Puente Aranda"},
    {"nombre": "La Camelia", "localidad": "Puente Aranda"},
    {"nombre": "La Fraguita", "localidad": "Puente Aranda"},
    {"nombre": "La Trinidad", "localidad": "Puente Aranda"},
    {"nombre": "Las Americas Occidental", "localidad": "Puente Aranda"},
    {"nombre": "Leon XIII", "localidad": "Puente Aranda"},
    {"nombre": "Muzú Sur", "localidad": "Puente Aranda"},
    {"nombre": "Ospina Perez", "localidad": "Puente Aranda"},
    {"nombre": "Pensilvania", "localidad": "Puente Aranda"},
    {"nombre": "San Rafael Noroccidental", "localidad": "Puente Aranda"},
    {"nombre": "Veraguas", "localidad": "Puente Aranda"},

    # LA CANDELARIA
    {"nombre": "La Candelaria", "localidad": "La Candelaria"},
    {"nombre": "Las Aguas", "localidad": "La Candelaria"},
    {"nombre": "La Catedral", "localidad": "La Candelaria"},
    {"nombre": "Egipto", "localidad": "La Candelaria"},
    {"nombre": "Belen", "localidad": "La Candelaria"},
    {"nombre": "Centro Historico", "localidad": "La Candelaria"},
    {"nombre": "La Concordia", "localidad": "La Candelaria"},
    {"nombre": "Las Nieves", "localidad": "La Candelaria"},
    {"nombre": "Santa Barbara", "localidad": "La Candelaria"},
    {"nombre": "Girardot", "localidad": "La Candelaria"},
    {"nombre": "La Alameda", "localidad": "La Candelaria"},
    {"nombre": "Santa Ines", "localidad": "La Candelaria"},
    {"nombre": "Veracruz", "localidad": "La Candelaria"},
    {"nombre": "Centro Internacional", "localidad": "La Candelaria"},
    {"nombre": "La Floresta", "localidad": "La Candelaria"},

    # RAFAEL URIBE URIBE
    {"nombre": "Rafael Uribe", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Marco Fidel Suarez", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Claret", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Diana Turbay", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "El Libertador", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Granjas de San Pablo", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "La Represa", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Marruecos", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Molinos", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "San Agustin", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "San Jose Sur", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Santander", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Sotavento", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Valles de Cafam", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Villa del Cerro", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Alqueria La Fragua", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Arrayanal", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Bayona Norte", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Bello Horizonte", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Bravo Paez", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Ciudad Jardin Sur", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "El Consuelo", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "El Mochuelo", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "El Triunfo", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "La Colorada", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "La Picota", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Las Lomas", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Olaya", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Quiroga", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "San Jose de Castilla", "localidad": "Rafael Uribe Uribe"},

    # CIUDAD BOLÍVAR
    {"nombre": "Lucero", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Paraiso", "localidad": "Ciudad Bolivar"},
    {"nombre": "Arborizadora Alta", "localidad": "Ciudad Bolivar"},
    {"nombre": "San Francisco", "localidad": "Ciudad Bolivar"},
    {"nombre": "Sierra Morena", "localidad": "Ciudad Bolivar"},
    {"nombre": "Meissen", "localidad": "Ciudad Bolivar"},
    {"nombre": "Candelaria La Nueva", "localidad": "Ciudad Bolivar"},
    {"nombre": "Ismael Perdomo", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Tesoro", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Mochuelo", "localidad": "Ciudad Bolivar"},
    {"nombre": "Arborizadora Baja", "localidad": "Ciudad Bolivar"},
    {"nombre": "Bella Flor", "localidad": "Ciudad Bolivar"},
    {"nombre": "Jerusalem", "localidad": "Ciudad Bolivar"},
    {"nombre": "Las Manitas", "localidad": "Ciudad Bolivar"},
    {"nombre": "Perdomo Alto", "localidad": "Ciudad Bolivar"},
    {"nombre": "Quiba", "localidad": "Ciudad Bolivar"},
    {"nombre": "Tesoro Alto", "localidad": "Ciudad Bolivar"},
    {"nombre": "Vista Hermosa", "localidad": "Ciudad Bolivar"},
    {"nombre": "Mochuelo Alto", "localidad": "Ciudad Bolivar"},
    {"nombre": "Mochuelo Bajo", "localidad": "Ciudad Bolivar"},
    {"nombre": "Alpes", "localidad": "Ciudad Bolivar"},
    {"nombre": "Arrayanal", "localidad": "Ciudad Bolivar"},
    {"nombre": "Bilbao", "localidad": "Ciudad Bolivar"},
    {"nombre": "Casa de Teja", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Espino", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Oasis", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Paraiso II", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Recuerdo Sur", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Rincon", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Triangulo", "localidad": "Ciudad Bolivar"},
    {"nombre": "Juan Pablo II", "localidad": "Ciudad Bolivar"},
    {"nombre": "La Esmeralda", "localidad": "Ciudad Bolivar"},
    {"nombre": "La Gloria", "localidad": "Ciudad Bolivar"},
    {"nombre": "La Paz", "localidad": "Ciudad Bolivar"},
    {"nombre": "Lagartos", "localidad": "Ciudad Bolivar"},
    {"nombre": "Las Brisas", "localidad": "Ciudad Bolivar"},
    {"nombre": "Los Alpes", "localidad": "Ciudad Bolivar"},
    {"nombre": "San Joaquin", "localidad": "Ciudad Bolivar"},
    {"nombre": "Santa Viviana", "localidad": "Ciudad Bolivar"},
    {"nombre": "Compartir", "localidad": "Ciudad Bolivar"},

    # SUMAPAZ
    {"nombre": "San Juan de Sumapaz", "localidad": "Sumapaz"},
    {"nombre": "Nazareth", "localidad": "Sumapaz"},
    {"nombre": "Betania", "localidad": "Sumapaz"},
    {"nombre": "Concepcion", "localidad": "Sumapaz"},
    {"nombre": "Las Vegas", "localidad": "Sumapaz"},
    {"nombre": "Taquecitos", "localidad": "Sumapaz"},
    {"nombre": "La Unión", "localidad": "Sumapaz"},
    {"nombre": "Capitolio", "localidad": "Sumapaz"},
    {"nombre": "Chorreras", "localidad": "Sumapaz"},
    {"nombre": "El Toldo", "localidad": "Sumapaz"},
]