BARRIOS_BOGOTA = [
    # USAQUÉN
    {"nombre": "Cedritos", "localidad": "Usaquen"},
    {"nombre": "Santa Barbara", "localidad": "Usaquen"},
    {"nombre": "Chico Norte", "localidad": "Usaquen"},
    {"nombre": "Usaquen Centro", "localidad": "Usaquen"},
    {"nombre": "Verbenal", "localidad": "Usaquen"},
    {"nombre": "Toberin", "localidad": "Usaquen"},
    {"nombre": "San Cristobal Norte", "localidad": "Usaquen"},
    {"nombre": "Bella Suiza", "localidad": "Usaquen"},
    {"nombre": "Bosque de Pinos", "localidad": "Usaquen"},
    {"nombre": "El Codito", "localidad": "Usaquen"},
    {"nombre": "Horizontes", "localidad": "Usaquen"},
    {"nombre": "La Estrellita", "localidad": "Usaquen"},
    {"nombre": "Los Consuelos", "localidad": "Usaquen"},
    {"nombre": "Maranta", "localidad": "Usaquen"},
    {"nombre": "Maturin", "localidad": "Usaquen"},
    {"nombre": "Mirador del Norte", "localidad": "Usaquen"},
    {"nombre": "Nuevo Horizonte", "localidad": "Usaquen"},
    {"nombre": "San Antonio Norte", "localidad": "Usaquen"},
    {"nombre": "Tibabita", "localidad": "Usaquen"},
    {"nombre": "Villa del Mar", "localidad": "Usaquen"},

    # CHAPINERO
    {"nombre": "Chapinero Alto", "localidad": "Chapinero"},
    {"nombre": "Chapinero Central", "localidad": "Chapinero"},
    {"nombre": "Rosales", "localidad": "Chapinero"},
    {"nombre": "El Nogal", "localidad": "Chapinero"},
    {"nombre": "La Cabrera", "localidad": "Chapinero"},
    {"nombre": "Quinta Camacho", "localidad": "Chapinero"},
    {"nombre": "Marly", "localidad": "Chapinero"},
    {"nombre": "Bosque Calderon", "localidad": "Chapinero"},
    {"nombre": "Antiguo Country", "localidad": "Chapinero"},
    {"nombre": "El Retiro", "localidad": "Chapinero"},
    {"nombre": "La Salle", "localidad": "Chapinero"},
    {"nombre": "Pardo Rubio", "localidad": "Chapinero"},
    {"nombre": "Sagrado Corazon", "localidad": "Chapinero"},
    {"nombre": "Sucre", "localidad": "Chapinero"},
    {"nombre": "El Castillo", "localidad": "Chapinero"},
    {"nombre": "La Porciuncula", "localidad": "Chapinero"},
    {"nombre": "Emaus", "localidad": "Chapinero"},
    {"nombre": "El Refugio", "localidad": "Chapinero"},
    {"nombre": "Bellavista", "localidad": "Chapinero"},
    {"nombre": "Los Rosales", "localidad": "Chapinero"},

    # SANTA FE
    {"nombre": "La Candelaria", "localidad": "Santa Fe"},
    {"nombre": "Las Nieves", "localidad": "Santa Fe"},
    {"nombre": "La Macarena", "localidad": "Santa Fe"},
    {"nombre": "Egipto", "localidad": "Santa Fe"},
    {"nombre": "Lourdes", "localidad": "Santa Fe"},
    {"nombre": "Miraflores", "localidad": "Santa Fe"},
    {"nombre": "San Martin", "localidad": "Santa Fe"},
    {"nombre": "Alameda", "localidad": "Santa Fe"},
    {"nombre": "Bavaria", "localidad": "Santa Fe"},
    {"nombre": "Belén", "localidad": "Santa Fe"},
    {"nombre": "La Concordia", "localidad": "Santa Fe"},
    {"nombre": "La Perseverancia", "localidad": "Santa Fe"},
    {"nombre": "Paloquemao", "localidad": "Santa Fe"},
    {"nombre": "San Victorino", "localidad": "Santa Fe"},
    {"nombre": "Santa Barbara", "localidad": "Santa Fe"},

    # SAN CRISTÓBAL
    {"nombre": "20 de Julio", "localidad": "San Cristobal"},
    {"nombre": "San Blas", "localidad": "San Cristobal"},
    {"nombre": "La Victoria", "localidad": "San Cristobal"},
    {"nombre": "Altamira", "localidad": "San Cristobal"},
    {"nombre": "Villa de los Alpes", "localidad": "San Cristobal"},
    {"nombre": "San Ignacio", "localidad": "San Cristobal"},
    {"nombre": "San Javier", "localidad": "San Cristobal"},
    {"nombre": "San Martin", "localidad": "San Cristobal"},
    {"nombre": "San Rafael", "localidad": "San Cristobal"},
    {"nombre": "San Vicente", "localidad": "San Cristobal"},
    {"nombre": "Santa Ines", "localidad": "San Cristobal"},
    {"nombre": "Santa Lucia", "localidad": "San Cristobal"},
    {"nombre": "Santa Marta", "localidad": "San Cristobal"},
    {"nombre": "Santa Rosa", "localidad": "San Cristobal"},
    {"nombre": "Santa Teresa", "localidad": "San Cristobal"},
    {"nombre": "Santa Barbara", "localidad": "San Cristobal"},
    {"nombre": "Santa Helena", "localidad": "San Cristobal"},
    {"nombre": "Santa Isabel", "localidad": "San Cristobal"},
    {"nombre": "Santa Clara", "localidad": "San Cristobal"},
    {"nombre": "Santa Ana", "localidad": "San Cristobal"},

    # USME
    {"nombre": "Usme Centro", "localidad": "Usme"},
    {"nombre": "Santa Librada", "localidad": "Usme"},
    {"nombre": "Yomasa", "localidad": "Usme"},
    {"nombre": "Gran Yomasa", "localidad": "Usme"},
    {"nombre": "El Uval", "localidad": "Usme"},
    {"nombre": "El Nuevo Porvenir", "localidad": "Usme"},
    {"nombre": "Alfonso Lopez", "localidad": "Usme"},
    {"nombre": "La Flora", "localidad": "Usme"},
    {"nombre": "Chuniza", "localidad": "Usme"},
    {"nombre": "Comuneros", "localidad": "Usme"},
    {"nombre": "Danubio Azul", "localidad": "Usme"},
    {"nombre": "El Bosque", "localidad": "Usme"},
    {"nombre": "La Esperanza Sur", "localidad": "Usme"},
    {"nombre": "La Marichuela", "localidad": "Usme"},
    {"nombre": "Tocaimita", "localidad": "Usme"},

    # TUNJUELITO
    {"nombre": "Tunjuelito", "localidad": "Tunjuelito"},
    {"nombre": "Venecia", "localidad": "Tunjuelito"},
    {"nombre": "Abraham Lincoln", "localidad": "Tunjuelito"},
    {"nombre": "El Faro", "localidad": "Tunjuelito"},
    {"nombre": "El Tunal", "localidad": "Tunjuelito"},
    {"nombre": "Isla del Sol", "localidad": "Tunjuelito"},
    {"nombre": "San Benito", "localidad": "Tunjuelito"},
    {"nombre": "Sierra Morena", "localidad": "Tunjuelito"},
    {"nombre": "Nuevo Muzú", "localidad": "Tunjuelito"},
    {"nombre": "Rincón de Mutis", "localidad": "Tunjuelito"},

    # BOSA
    {"nombre": "Bosa Centro", "localidad": "Bosa"},
    {"nombre": "El Recreo", "localidad": "Bosa"},
    {"nombre": "San Bernardino", "localidad": "Bosa"},
    {"nombre": "La Libertad", "localidad": "Bosa"},
    {"nombre": "Porvenir", "localidad": "Bosa"},
    {"nombre": "Apogeo", "localidad": "Bosa"},
    {"nombre": "Bosa Nova", "localidad": "Bosa"},
    {"nombre": "Carlos Albán", "localidad": "Bosa"},
    {"nombre": "El Potrero", "localidad": "Bosa"},
    {"nombre": "Jimenez de Quesada", "localidad": "Bosa"},
    {"nombre": "La Amistad", "localidad": "Bosa"},
    {"nombre": "La Estacion", "localidad": "Bosa"},
    {"nombre": "Las Margaritas", "localidad": "Bosa"},
    {"nombre": "Laureles", "localidad": "Bosa"},
    {"nombre": "Palestina", "localidad": "Bosa"},
    {"nombre": "San Diego", "localidad": "Bosa"},
    {"nombre": "San Jose", "localidad": "Bosa"},
    {"nombre": "San Pablo", "localidad": "Bosa"},
    {"nombre": "Santa Fe", "localidad": "Bosa"},
    {"nombre": "Villa Nelly", "localidad": "Bosa"},

    # KENNEDY
    {"nombre": "Kennedy Central", "localidad": "Kennedy"},
    {"nombre": "Castilla", "localidad": "Kennedy"},
    {"nombre": "Tintal", "localidad": "Kennedy"},
    {"nombre": "Patio Bonito", "localidad": "Kennedy"},
    {"nombre": "Marsella", "localidad": "Kennedy"},
    {"nombre": "Timiza", "localidad": "Kennedy"},
    {"nombre": "Alqueria", "localidad": "Kennedy"},
    {"nombre": "Britalia", "localidad": "Kennedy"},
    {"nombre": "Villa Alsacia", "localidad": "Kennedy"},
    {"nombre": "Carvajal", "localidad": "Kennedy"},
    {"nombre": "La Igualdad", "localidad": "Kennedy"},
    {"nombre": "Americas", "localidad": "Kennedy"},
    {"nombre": "Bavaria", "localidad": "Kennedy"},
    {"nombre": "Corabastos", "localidad": "Kennedy"},
    {"nombre": "Gran Americas", "localidad": "Kennedy"},
    {"nombre": "La Alameda", "localidad": "Kennedy"},
    {"nombre": "Las Margaritas", "localidad": "Kennedy"},
    {"nombre": "Mandalay", "localidad": "Kennedy"},
    {"nombre": "Techo", "localidad": "Kennedy"},
    {"nombre": "Verona", "localidad": "Kennedy"},

    # FONTIBÓN
    {"nombre": "Fontibon Centro", "localidad": "Fontibon"},
    {"nombre": "Villemar", "localidad": "Fontibon"},
    {"nombre": "Capellania", "localidad": "Fontibon"},
    {"nombre": "Modelia", "localidad": "Fontibon"},
    {"nombre": "San Pablo", "localidad": "Fontibon"},
    {"nombre": "Aeropuerto El Dorado", "localidad": "Fontibon"},
    {"nombre": "Bahia", "localidad": "Fontibon"},
    {"nombre": "Ciudad Hayuelos", "localidad": "Fontibon"},
    {"nombre": "El Carmen", "localidad": "Fontibon"},
    {"nombre": "El Refugio", "localidad": "Fontibon"},
    {"nombre": "La Cabaña", "localidad": "Fontibon"},
    {"nombre": "La Estacion", "localidad": "Fontibon"},
    {"nombre": "La Isla", "localidad": "Fontibon"},
    {"nombre": "Puerta de Teja", "localidad": "Fontibon"},
    {"nombre": "Sabana Grande", "localidad": "Fontibon"},
    {"nombre": "San Jose", "localidad": "Fontibon"},
    {"nombre": "Zona Franca", "localidad": "Fontibon"},

    # ENGATIVÁ
    {"nombre": "Engativa Pueblo", "localidad": "Engativa"},
    {"nombre": "Modelia", "localidad": "Engativa"},
    {"nombre": "Normandia", "localidad": "Engativa"},
    {"nombre": "Boyaca Real", "localidad": "Engativa"},
    {"nombre": "Garces Navas", "localidad": "Engativa"},
    {"nombre": "Las Ferias", "localidad": "Engativa"},
    {"nombre": "Minuto de Dios", "localidad": "Engativa"},
    {"nombre": "Santa Helenita", "localidad": "Engativa"},
    {"nombre": "La Estrada", "localidad": "Engativa"},
    {"nombre": "Bolivia", "localidad": "Engativa"},
    {"nombre": "Bonanza", "localidad": "Engativa"},
    {"nombre": "El Encanto", "localidad": "Engativa"},
    {"nombre": "Florencia", "localidad": "Engativa"},
    {"nombre": "La Cabaña", "localidad": "Engativa"},
    {"nombre": "La Palmera", "localidad": "Engativa"},
    {"nombre": "La Riviera", "localidad": "Engativa"},
    {"nombre": "Las Mercedes", "localidad": "Engativa"},
    {"nombre": "Quirigua", "localidad": "Engativa"},
    {"nombre": "Santa Cecilia", "localidad": "Engativa"},
    {"nombre": "Villa Luz", "localidad": "Engativa"},

    # SUBA
    {"nombre": "Suba Centro", "localidad": "Suba"},
    {"nombre": "Niza", "localidad": "Suba"},
    {"nombre": "Gratamira", "localidad": "Suba"},
    {"nombre": "Tibabuyes", "localidad": "Suba"},
    {"nombre": "Villa del Prado", "localidad": "Suba"},
    {"nombre": "Aures", "localidad": "Suba"},
    {"nombre": "La Campina", "localidad": "Suba"},
    {"nombre": "Compartir", "localidad": "Suba"},
    {"nombre": "Rincon", "localidad": "Suba"},
    {"nombre": "San Jose de Bavaria", "localidad": "Suba"},
    {"nombre": "Lisboa", "localidad": "Suba"},
    {"nombre": "Prado Veraniego", "localidad": "Suba"},
    {"nombre": "San Cipriano", "localidad": "Suba"},
    {"nombre": "La Alborada", "localidad": "Suba"},
    {"nombre": "El Pinar", "localidad": "Suba"},
    {"nombre": "La Gaitana", "localidad": "Suba"},
    {"nombre": "Mazuren", "localidad": "Suba"},
    {"nombre": "La Toscana", "localidad": "Suba"},
    {"nombre": "El Batan", "localidad": "Suba"},
    {"nombre": "San Pedro de Tibabuyes", "localidad": "Suba"},

    # BARRIOS UNIDOS
    {"nombre": "Doce de Octubre", "localidad": "Barrios Unidos"},
    {"nombre": "Los Alcazares", "localidad": "Barrios Unidos"},
    {"nombre": "Polo Club", "localidad": "Barrios Unidos"},
    {"nombre": "Salitre", "localidad": "Barrios Unidos"},
    {"nombre": "Andes", "localidad": "Barrios Unidos"},
    {"nombre": "Avenida El Dorado", "localidad": "Barrios Unidos"},
    {"nombre": "Benjamín Herrera", "localidad": "Barrios Unidos"},
    {"nombre": "Colombia", "localidad": "Barrios Unidos"},
    {"nombre": "El Rosario", "localidad": "Barrios Unidos"},
    {"nombre": "Jorge Eliecer Gaitan", "localidad": "Barrios Unidos"},
    {"nombre": "La Castellana", "localidad": "Barrios Unidos"},
    {"nombre": "La Patria", "localidad": "Barrios Unidos"},
    {"nombre": "Meissen", "localidad": "Barrios Unidos"},
    {"nombre": "Niza Sur", "localidad": "Barrios Unidos"},
    {"nombre": "Rionegro", "localidad": "Barrios Unidos"},

    # TEUSAQUILLO
    {"nombre": "Teusaquillo", "localidad": "Teusaquillo"},
    {"nombre": "Palermo", "localidad": "Teusaquillo"},
    {"nombre": "Galerías", "localidad": "Teusaquillo"},
    {"nombre": "La Soledad", "localidad": "Teusaquillo"},
    {"nombre": "Nicolás de Federman", "localidad": "Teusaquillo"},
    {"nombre": "Armenia", "localidad": "Teusaquillo"},
    {"nombre": "Ciudad Salitre Oriental", "localidad": "Teusaquillo"},
    {"nombre": "Ciudad Salitre Occidental", "localidad": "Teusaquillo"},
    {"nombre": "El Campín", "localidad": "Teusaquillo"},
    {"nombre": "La Esmeralda", "localidad": "Teusaquillo"},
    {"nombre": "Parque Simón Bolívar", "localidad": "Teusaquillo"},
    {"nombre": "Quinta Paredes", "localidad": "Teusaquillo"},
    {"nombre": "San Luis", "localidad": "Teusaquillo"},
    {"nombre": "Santa Matilde", "localidad": "Teusaquillo"},
    {"nombre": "Veinte de Julio", "localidad": "Teusaquillo"},

    # LOS MÁRTIRES
    {"nombre": "La Sabana", "localidad": "Los Martires"},
    {"nombre": "Santa Isabel", "localidad": "Los Martires"},
    {"nombre": "Ricaurte", "localidad": "Los Martires"},
    {"nombre": "Eduardo Santos", "localidad": "Los Martires"},
    {"nombre": "El Listón", "localidad": "Los Martires"},
    {"nombre": "La Pepita", "localidad": "Los Martires"},
    {"nombre": "Samper Mendoza", "localidad": "Los Martires"},
    {"nombre": "Voto Nacional", "localidad": "Los Martires"},

    # ANTONIO NARIÑO
    {"nombre": "Ciudad Jardín Sur", "localidad": "Antonio Nariño"},
    {"nombre": "Restrepo", "localidad": "Antonio Nariño"},
    {"nombre": "Santander", "localidad": "Antonio Nariño"},
    {"nombre": "Antonio Nariño", "localidad": "Antonio Nariño"},
    {"nombre": "Policarpa", "localidad": "Antonio Nariño"},
    {"nombre": "Asuncion", "localidad": "Antonio Nariño"},
    {"nombre": "Consuelo", "localidad": "Antonio Nariño"},
    {"nombre": "Carvajal", "localidad": "Antonio Nariño"},
    {"nombre": "Murillo", "localidad": "Antonio Nariño"},
    {"nombre": "San Antonio", "localidad": "Antonio Nariño"},

    # PUENTE ARANDA
    {"nombre": "Puente Aranda", "localidad": "Puente Aranda"},
    {"nombre": "Muzú", "localidad": "Puente Aranda"},
    {"nombre": "Zona Industrial", "localidad": "Puente Aranda"},
    {"nombre": "Galán", "localidad": "Puente Aranda"},
    {"nombre": "Cundinamarca", "localidad": "Puente Aranda"},
    {"nombre": "El Penon", "localidad": "Puente Aranda"},
    {"nombre": "Fuentes", "localidad": "Puente Aranda"},
    {"nombre": "La Pradera", "localidad": "Puente Aranda"},
    {"nombre": "Las Americas", "localidad": "Puente Aranda"},
    {"nombre": "Salazar Gomez", "localidad": "Puente Aranda"},
    {"nombre": "San Rafael Industrial", "localidad": "Puente Aranda"},
    {"nombre": "Valladolid", "localidad": "Puente Aranda"},

    # LA CANDELARIA
    {"nombre": "La Candelaria", "localidad": "La Candelaria"},
    {"nombre": "Las Aguas", "localidad": "La Candelaria"},
    {"nombre": "La Catedral", "localidad": "La Candelaria"},
    {"nombre": "Egipto", "localidad": "La Candelaria"},
    {"nombre": "Belén", "localidad": "La Candelaria"},

    # RAFAEL URIBE URIBE
    {"nombre": "Rafael Uribe", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Marco Fidel Suarez", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Claret", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Diana Turbay", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "El Libertador", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Granjas de San Pablo", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "La Represa", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Marruecos", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Molinos", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "San Agustin", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "San Jose Sur", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Santander", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Sotavento", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Valles de Cafam", "localidad": "Rafael Uribe Uribe"},
    {"nombre": "Villa del Cerro", "localidad": "Rafael Uribe Uribe"},

    # CIUDAD BOLÍVAR
    {"nombre": "Lucero", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Paraiso", "localidad": "Ciudad Bolivar"},
    {"nombre": "Arborizadora Alta", "localidad": "Ciudad Bolivar"},
    {"nombre": "San Francisco", "localidad": "Ciudad Bolivar"},
    {"nombre": "Sierra Morena", "localidad": "Ciudad Bolivar"},
    {"nombre": "Meissen", "localidad": "Ciudad Bolivar"},
    {"nombre": "Candelaria La Nueva", "localidad": "Ciudad Bolivar"},
    {"nombre": "Ismael Perdomo", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Tesoro", "localidad": "Ciudad Bolivar"},
    {"nombre": "El Mochuelo", "localidad": "Ciudad Bolivar"},
    {"nombre": "Arborizadora Baja", "localidad": "Ciudad Bolivar"},
    {"nombre": "Bella Flor", "localidad": "Ciudad Bolivar"},
    {"nombre": "Jerusalem", "localidad": "Ciudad Bolivar"},
    {"nombre": "Las Manitas", "localidad": "Ciudad Bolivar"},
    {"nombre": "Perdomo Alto", "localidad": "Ciudad Bolivar"},
    {"nombre": "Quiba", "localidad": "Ciudad Bolivar"},
    {"nombre": "Tesoro Alto", "localidad": "Ciudad Bolivar"},
    {"nombre": "Vista Hermosa", "localidad": "Ciudad Bolivar"},
    {"nombre": "Mochuelo Alto", "localidad": "Ciudad Bolivar"},
    {"nombre": "Mochuelo Bajo", "localidad": "Ciudad Bolivar"},

    # SUMAPAZ
    {"nombre": "San Juan de Sumapaz", "localidad": "Sumapaz"},
    {"nombre": "Nazareth", "localidad": "Sumapaz"},
    {"nombre": "Betania", "localidad": "Sumapaz"},
    {"nombre": "Concepcion", "localidad": "Sumapaz"},
    {"nombre": "Las Vegas", "localidad": "Sumapaz"},
]