from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('quienes/', views.quienes, name='quienes'),
    path('contacto/', views.contacto, name='contacto'),
    path('contactousu/', views.contactousu, name='contactousu'),
    path('menu/', views.menu, name='menu'),
    path('paginaNo/', views.paginaNo, name='paginaNo'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registro_cliente, name='registro'),
    path('crear-repartidor/', views.crear_repartidor, name='crear_repartidor'),
    path('crear-admin/', views.crear_admin, name='crear_admin'),
    path('usuario/', views.usuario, name='usuario'),
    path('repartidor/', views.repartidor, name='repartidor'),
    path('panel-admin/', views.admin, name='panel_admin'),
    path('sinacceso/', views.sinacceso, name='sinacceso'),
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('actualizar/', views.actualizar_usuario, name='actualizar_usuario'),
    path('eliminar-usuario/<int:id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('mis_pedidos/', views.mis_pedidos, name='mis_pedidos'),
    path('pedidos/disponibles/', views.pedidos_disponibles, name='pedidos_disponibles'),
    path('pedidos/tomar/<int:pedido_id>/', views.tomar_pedido, name='tomar_pedido'),
    path('pedidos/entregar/<int:pedido_id>/', views.entregar_pedido, name='entregar_pedido'),
    path('pedidos/detalle/<int:pedido_id>/', views.detalle_pedido, name='detalle_pedido'),
    path('sugerencias/', views.sugerencias, name='sugerencias'),
    path('panel-sugerencias/', views.panel_sugerencias, name='panel_sugerencias'),
    path('restablecer/', views.restablecer_password, name='restablecer'),
    path('nueva_contrasena/<str:token>/', views.nueva_contrasena, name='nueva_contrasena'),
    path('nueva_contrasena/', views.nueva_contrasena, name='nueva_contrasena_sin_token'),
    path("prueba-correo/", views.prueba_correo),
    path('api/localidades-bogota/', views.localidades_bogota, name='api_localidades'),
    path('api/barrios-bogota/', views.barrios_bogota, name='api_barrios'),
    
]