from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('quienes/', views.quienes, name='quienes'),
    path('contacto/', views.contacto, name='contacto'),
    path('login/', views.login_view, name='login'),
    path('registro/', views.registro_cliente, name='registro'),
    path('menu/', views.menu, name='menu'),
    path('crear-repartidor/', views.crear_repartidor, name='crear-repartidor'),
    path('usuario/', views.usuario, name='usuario'),
    path('sinacceso/', views.sinacceso, name='sinacceso'),
    path('repartidor/', views.repartidor, name='repartidor'),
    path('logout/', views.logout_view, name='logout'),
    path('sugerencias/', views.sugerencias, name='sugerencias'),
    path('productos/', views.productos, name='productos'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('inventario/', views.inventario, name='inventario'),
    path('crear-admin/', views.crear_admin, name='crear_admin'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('panel-admin/', views.admin, name='panel_admin'),
    path('detalle-pedido/', views.detalle_pedido, name='detalle_pedido'),
    path('carrito/', views.carrito, name='carrito'),
    path('contactousu/', views.contactousu, name='contactousu'),
    path('formulario_compra/', views.formulario_compra, name='formulario_compra'),
    path('producto/<slug:slug>/', views.producto_detalle, name='producto-detalle'),
    path('paginaNo/', views.paginaNo, name='paginaNo'),
    path('actualizar/', views.actualizar_usuario, name='actualizar_usuario'),
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('factura/', views.factura, name='factura'),
    path('generar-pdf/', views.generar_pdf, name='generar_pdf'),
    path('reportes-ventas/', views.reportesVentas, name='reportesVentas'),
    path('producto-nuevo/', views.producto_nuevo, name='producto_nuevo'),
    path('producto/<int:id>/', views.producto_detalle, name='producto_detalle'),
    path('producto-editar/<int:id>/', views.producto_editar, name='producto_editar'),
    path('producto-eliminar/<int:id>/', views.producto_eliminar, name='producto_eliminar'),
    path('eliminar-usuario/<int:id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('restablecer/', views.restablecer_password, name='restablecer'),
    path('nueva_contrasena/<str:token>/', views.nueva_contrasena, name='nueva_contrasena'),
    path('nueva_contrasena/', views.nueva_contrasena, name='nueva_contrasena'),
    path("prueba-correo/", views.prueba_correo),
    path('agregar_stock/<int:id>/', views.agregar_stock, name='agregar_stock'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),

]