# Generated by Django 6.0.2 on 2026-02-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('usuCorreo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('usuTelefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateField()),
                ('barrio', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('resetToken', models.CharField(blank=True, max_length=255, null=True)),
                ('tokenExpiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
