# Generated by Django 6.0.2 on 2026-02-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(default='usuario', max_length=20),
        ),
    ]
