# Generated by Django 6.0.3 on 2026-03-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=10),
            preserve_default=False,
        ),
    ]
