# Generated by Django 6.0.4 on 2026-06-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='DetalleVentaProductos',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
