# Generated by Django 6.0.2 on 2026-03-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
