# Generated by Django 6.0.3 on 2026-03-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_administrador_id_alter_asignacion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.repartidor')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
    ]
