# Generated by Django 6.0.3 on 2026-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_movimiento_proveedor_movimiento_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('mixto', 'Mixto')], max_length=20, null=True),
        ),
    ]
