# Generated by Django 6.0.4 on 2026-06-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_venta_detalleventa_duplicates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallaproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TallaProducto',
        ),
    ]
