# Generated by Django 6.0.3 on 2026-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tallaproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='talla',
            field=models.CharField(default='M', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
