# Generated by Django 6.0.4 on 2026-06-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_producto_movimiento_talla_duplicates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Sugerencia',
        ),
    ]
