# Generated by Django 6.0.3 on 2026-03-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
