# Generated by Django 6.0.2 on 2026-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_reporte_sugerencia_proveedor_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionrepartidor',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
