# Generated by Django 6.0.2 on 2026-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
