# Generated by Django 6.0.2 on 2026-06-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('es_admin', models.BooleanField(default=False)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='usuarios.repartidor')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
